default_platform(:ios)

platform :ios do
  before_all do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"],
      duration: 1200,
      in_house: false
    )
  end

  lane :release do
    produce(
      app_identifier: "com.melmarion.thewitness",
      app_name: "The Witness",
      team_id: "Q242KWQD56"
    )
    build_app(
      project: "TheWitness.xcodeproj",
      scheme: "TheWitness",
      clean: true,
      export_method: "app-store",
      export_options: "./ExportOptions.plist",
      xcargs: "CODE_SIGN_STYLE=Manual DEVELOPMENT_TEAM=Q242KWQD56 CODE_SIGN_IDENTITY='Apple Distribution: MARION MORANETZ (Q242KWQD56)' PROVISIONING_PROFILE_SPECIFIER='com.melmarion.thewitness AppStore'"
    )
    upload_to_app_store(
      skip_screenshots: true,
      skip_metadata: true,
      team_id: "Q242KWQD56",
      force: true
    )
  end
end
